### ISSUE TITLE
Failed to execute 'removeChild'

### ISSUE THREAD

**Issue by spaceywolfi** [stfalcon-studio/stf-vue-select#7]
Everything is working just fine, however when I change my page (using vue-router) i always get this error in the console from stf-vue-select.
I am using stf-vue-select in my main-layout which every page uses.

```
[Vue warn]: Error in beforeDestroy hook: "NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node."

found in

---> <StfSelect>
        <USelect> at src/components/core/USelect.vue
         <LangSelector> at src/components/LangSelector.vue
           <MainMenu> at src/layouts/MainMenu.vue
             <MdToolbar>
               <MdAppToolbar>
                 <MdAppInternalSideDrawer>
                   <MainLayout> at src/layouts/MainLayout.vue
                     <Home> at src/pages/Home.vue
                       <App> at src/App.vue
                         <Root>




vue.esm.js?efeb:1696 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at VueComponent.beforeDestroy (webpack-internal:///./node_modules/flexible-vue-select/dist/lib/stf-vue-select.min.js:1:12811)
    at callHook (webpack-internal:///./node_modules/vue/dist/vue.esm.js:2869:21)
    at VueComponent.Vue.$destroy (webpack-internal:///./node_modules/vue/dist/vue.esm.js:2654:5)
    at destroy (webpack-internal:///./node_modules/vue/dist/vue.esm.js:4066:27)
    at invokeDestroyHook (webpack-internal:///./node_modules/vue/dist/vue.esm.js:5600:59)
    at VueComponent.patch [as __patch__] (webpack-internal:///./node_modules/vue/dist/vue.esm.js:5923:30)
    at VueComponent.Vue.$destroy (webpack-internal:///./node_modules/vue/dist/vue.esm.js:2677:8)
    at destroy (webpack-internal:///./node_modules/vue/dist/vue.esm.js:4066:27)
    at invokeDestroyHook (webpack-internal:///./node_modules/vue/dist/vue.esm.js:5600:59)
    at VueComponent.patch [as __patch__] (webpack-internal:///./node_modules/vue/dist/vue.esm.js:5923:30)
```

**Comment by AndreySyagrovskiy** [comment]
@spaceywolfi  What version do you use?

**Comment by AndreySyagrovskiy** [comment]
@spaceywolfi can you give the example of bug at service like this https://plnkr.co/?
